---
# tasks file for roles/pve
- name: Enable non enterprise repositories
  block:
    - name: Disable proxmox enterprise repository
      replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: "^deb"
        replace: "#deb"

    - name: Disable ceph enterprise repository
      replace:
        path: /etc/apt/sources.list.d/ceph.list
        regexp: "^deb"
        replace: "#deb"

    - name: Add no subscription proxmox repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/pve {{ pve_debian_release }} pve-no-subscription"

    - name: Add no subscription ceph repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/ceph-quincy {{ pve_debian_release }} no-subscription"
  notify: dist upgrade

- name: Disable proxmox no subscription popup
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: '^(.*)Ext\.Msg\.show\(\{(.*)$\n^(.*)No valid subscription(.*)$'
    replace: '\1void({\2\n\3No valid subscription\4'
    backup: true

- name: Install requried packages
  apt: 
    name:
      - python3-proxmoxer
      - python3-requests
      - htop
      - sudo
      - vim
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Load modules for GVT-G
  modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_items:
    - kvmgt
    - mdev
    - vfio-iommu-type1

- name: Enable intel_iommu and GVT-G
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=*"
    line: GRUB_CMDLINE_LINUX_DEFAULT="quite intel_iommu=on i915.enable_gvt=1"
  notify: 
    - update grub
    - update Initramfs
    - reboot