---
# vars file for dockercompose
docker_base_dir: "{{ ansible_user_dir }}/docker"
docker_volume_dir: "{{ docker_base_dir }}/volumes"
docker_compose_dir_remote: "{{ docker_base_dir }}/compose"
docker_compose_dir_local: "./templates"
docker_compose_version: "3.8"

nfs_nextcloud_dir: "/mnt/tank/nextcloud"
nfs_vaultwarden_dir: "/mnt/tank/vaultwarden"
nfs_downloads_dir: "/mnt/tank/media/downloads"
nfs_movies_dir: "/mnt/tank/media/movies"
nfs_shows_dir: "/mnt/tank/media/shows"
nfs_gitea_dir: "/mnt/tank/git/repo"
nfs_share_dir: "/mnt/tank/share"

timezone: "Asia/Kolkata"
uid: "1000"
gid: "3000"

containers:
  traefik: 
    name: "traefik"
    image: "traefik"
    auth: "{{ basic_auth }}"
    network: "traefik"
  portainer: 
    name: "portainer"
    image: "portainer/portainer-ce"
  nextcloud: 
    name: "nextcloud"
    image: "lscr.io/linuxserver/nextcloud"
  nextcloud_db:
    name: "nextcloud_db"
    image: "lscr.io/linuxserver/mariadb"
  vaultwarden:
    name: "vaultwarden"
    image: "vaultwarden/server"
  code:
    name: "code"
    image: "lscr.io/linuxserver/openvscode-server"
  gitea:
    name: "gitea"
    image: "gitea/gitea"
  pyload:
    name: "pyload"
    image: "lscr.io/linuxserver/pyload-ng"
  jellyfin:
    name: "jellyfin"
    image: "lscr.io/linuxserver/jellyfin"
  qbittorrent:
    name: "qbittorrent"
    image: "lscr.io/linuxserver/qbittorrent"
  transmission:
    name: "transmission"
    image: "lscr.io/linuxserver/transmission"
  guacamole:
    name: "guacamole"
    image: "oznu/guacamole"
  microbin:
    name: "mircobin"
    image: "danielszabo99/microbin"
  searx:
    name: "searx"
    image: "searx/searx"
  actual:
    name: "actual"
    image: "ghcr.io/actualbudget/actual-server"
  snipeit:
    name: "snipeit"
    image: "lscr.io/linuxserver/snipe-it"
  snipeit_db:
    name: "snipeit_db"
    image: "lscr.io/linuxserver/mariadb"
  freshrss:
    name: "freshrss"
    image: "lscr.io/linuxserver/freshrss"

  flaresolverr:
    name: "flaresolverr"
    image: " flaresolverr/flaresolverr"
  prowlarr:
    name: "prowlarr"
    image: "lscr.io/linuxserver/prowlarr"
  sonarr:
    name: "sonarr"
    image: "lscr.io/linuxserver/sonarr"
  radarr:
    name: "radarr"
    image: "lscr.io/linuxserver/radarr"
  bazarr:
    name: "bazarr"
    image: "lscr.io/linuxserver/bazarr"
  jellyseer:
    name: "jellyseer"
    image: "fallenbagel/jellyseerr"
  homepage:
    name: "homepage"
    image: "ghcr.io/benphelps/homepage"
  
